from pathlib import Path

p = Path('apps/arstack_studio/src/DeterministicSessionHarness.cpp')
text = p.read_text(encoding='utf-8')
if 'static bool firmwareStageProjectionIsExplicit()' in text:
    print('P0 regression functions already present')
    raise SystemExit(0)

anchor = '''    static bool automaticIdentityTimeoutOffersFirmwareRecovery() {\n'''
insert = '''    static bool firmwareStageProjectionIsExplicit() {\n        Fixture fixture;\n        auto& session = fixture.session;\n        session.updateStage_ = SmartSessionController::UpdateStage::idle;\n        const bool idle = session.firmwareUpdateStage() == QStringLiteral("idle");\n        session.updateStage_ = SmartSessionController::UpdateStage::stopping;\n        const bool stopping = session.firmwareUpdateStage() == QStringLiteral("prepare");\n        session.updateStage_ = SmartSessionController::UpdateStage::releasingPort;\n        const bool releasing = session.firmwareUpdateStage() == QStringLiteral("prepare");\n        session.updateStage_ = SmartSessionController::UpdateStage::probing;\n        const bool probing = session.firmwareUpdateStage() == QStringLiteral("verify");\n        session.updateStage_ = SmartSessionController::UpdateStage::flashing;\n        const bool flashing = session.firmwareUpdateStage() == QStringLiteral("write");\n        session.updateStage_ = SmartSessionController::UpdateStage::reconnecting;\n        const bool reconnecting = session.firmwareUpdateStage() == QStringLiteral("reconnect");\n        session.updateStage_ = SmartSessionController::UpdateStage::waitingForBootloader;\n        const bool bootloader = session.firmwareUpdateStage() == QStringLiteral("verify");\n        return idle && stopping && releasing && probing && flashing && reconnecting && bootloader;\n    }\n\n    static bool fragmentedEspflashProgressIsMonotonic() {\n        Fixture fixture;\n        auto& firmware = fixture.firmware;\n        firmware.operation_ = FirmwareManager::Operation::flash;\n        firmware.flashProgress_ = -1;\n        firmware.progressOutputTail_.clear();\n\n        firmware.updateProgressFromOutput(QString::fromLatin1("\\x1B[2K\\r[00:00:01] [================] 4"));\n        const bool remainsUnknown = firmware.flashProgress_ == -1;\n        firmware.updateProgressFromOutput(QStringLiteral("2/100 segment 0x0\\r"));\n        const bool reconstructsSplitCounter = firmware.flashProgress_ == 42;\n        firmware.updateProgressFromOutput(QStringLiteral("[00:00:02] [========] 21/100 segment 0x0\\r"));\n        const bool neverMovesBackward = firmware.flashProgress_ == 42;\n        firmware.updateProgressFromOutput(QStringLiteral("[00:00:03] [========================================] 100/100 segment 0x0\\r"));\n        const bool reachesCompletion = firmware.flashProgress_ == 100;\n\n        return remainsUnknown && reconstructsSplitCounter && neverMovesBackward && reachesCompletion &&\n            FirmwareManager::parseFlashProgress(QStringLiteral("Writing 64%\\r")) == 64 &&\n            FirmwareManager::parseFlashProgress(QStringLiteral("[00:00:02] [================] 17/20 segment 0x10000")) == 85 &&\n            FirmwareManager::parseFlashProgress(QStringLiteral("21/0 segment 0x0")) == -1;\n    }\n\n'''
if anchor not in text:
    raise SystemExit('P0 regression insertion anchor not found')
p.write_text(text.replace(anchor, insert + anchor, 1), encoding='utf-8')
print('P0 regression functions inserted')
